### ISSUE TITLE
Error: Cannot find module '../inter.json'

### ISSUE THREAD

**Issue by Rizary** [semencov/tailwindcss-font-inter#1]
So, I try to use this module, and my build system download the package through `https://registry.npmjs,org/tailwindcss-font-inter/-/tailwindcss-font-inter-1.0.5.tgz`

but it appears that the file doesn't contain `inter.json` when I extract it (along with other version). Would you mind to include the `inter.json` everytime you push it to npm website?

**Comment by Rizary** [comment]
Maybe this reference can help you figure out the problem:
https://stackoverflow.com/questions/27049192/npm-publish-isnt-including-all-my-files

**Comment by semencov** [comment]
Thank you. This is my fault, I forgot to specify it in package.json. Fixed in [v1.0.6](https://github.com/semencov/tailwindcss-font-inter/releases/tag/v1.0.6).

**Comment by Rizary** [comment]
@semencov great!
