### ISSUE TITLE
unable to overwrite letter-spacing applied by .font-inter.text-[size]

### ISSUE THREAD

**Issue by brumm** [semencov/tailwindcss-font-inter#10]
Hey, thanks for this awesome plugin!

It seems that when using `font-inter`, I'm unable to overwrite the default letter-spacing that is automatically applied with the font.

Check out the repro case here: https://play.tailwindcss.com/nEAxqOYef2

**Comment by semencov** [comment]
@brumm, thanks for the report. This is a really unpleasant drawback of the plugin. However, at the moment I do not have a clear vision of how this should be implemented:

* Should the Dynamic Metrics be ignored if a specific tracking class is used?
* Should the letter-spacing be calculated relative to the Dynamic Metrics and specified spacing?
* Should the default letter-spacing be optional (separate utility-class)?

So, I'm waiting for your suggestions and will try to do my best.

**Comment by brumm** [comment]
I'd be super happy with a simple config option to turn off generation of the extra `.font-inter.text-[size]` classes. The Dynamic metrics are certainly nice, but not the deciding factor for me in using this plugin.

**Comment by semencov** [comment]
I'm not quite sure then why use the plugin? It does only three things at the moment: adds font-face (by default); creates Inter's specific pairs of font sizes and letter-spacings; creates set of `font-feature-settings` utilities. And two of these three features can be implemented with different plugins or with no plugins at all. The Dynamic Metrics are the main custom feature of the plugin, I guess. So, if you disable globally this feature, what would be the value of using it?

**Comment by brumm** [comment]
I see :) I picked this plugin because it provides a super easy way of adding the inter font and hooking it up to tailwind with a single line of plugin config.

I love the font-feature-settings stuff as well. I also do like the Dynamic Metrics feature, but I could live without it, especially if it keeps me from applying letter-spacing.

Do you have a suggestion for a similar plugin out there that does things as nicely as yours?

**Comment by brumm** [comment]
That said, making Dynamic Metrics optional was only one of three solutions you suggested. Maybe there's a way to have the best of both worlds?

**Comment by semencov** [comment]
No, I don't know any. This is why I had to implement my own 😄 

Well, I guess I'll stick with the Dynamic Metrics approach: I'll try to calculate the letter-spacing relative to the DM and tracking modifier. Just as it has done on the Inter's demo page: https://rsms.me/inter/dynmetrics/

But do not expect the new version before the beginning of April. Unfortunatelly, I'm completely out of time at the moment.

Stay in touch.

**Comment by semencov** [comment]
Letter-spacing support will be released in v3.0.0 (currently in `dev` branch).
