### ISSUE TITLE
Prevent layout shifts with font-display

### ISSUE THREAD

**Issue by Hassan1984** [semencov/tailwindcss-font-inter#21]
Thanks for the great plugin. It's working great. I'm facing an issue where our layout shifts until the font is loaded because `font-display` is set to `swap`. Is there any reason why `font-display` is set to `swap` instead of `optional`?

**Comment by semencov** [comment]
The font definition comes from https://rsms.me/inter/inter.css. So I would like not to change it. Otherwise if you set option `importFontFace: false`, you could add your font face definition by yourself.

**Comment by Hassan1984** [comment]
thanks for the quick response. I will try that.
