### ISSUE TITLE
How to customize font location?

### ISSUE THREAD

**Issue by jmas** [semencov/tailwindcss-font-inter#24]
Hello. I'm trying to figure out how to replace import `@import url('https://rsms.me/inter/inter.css');` to use local version of font, not from `rsms.me` host. 

Why I need to use local font? Google Page Insights show problem with loading font from `rsms.me` host – it takes too much time.

The promlem – I can't figure out which plugin add this import. I gues it uses `tailwindcss-font-inter` under the hood.

**Question:** How to remove import `@import url('https://rsms.me/inter/inter.css');` from Tailwind output CSS file? How to add import from local host?

Thank you for your attention.

**Comment by semencov** [comment]
The plugin imports fonts from rsms.me by default. To disable import you just need to set `importFontFace` to false in config:

```js
module.exports = {
  /* ... */
  plugins: [
    require('tailwindcss-font-inter')({
      importFontFace: false
    })
  ]
}

```

**Comment by jmas** [comment]
@semencov Thank you for your help!
