### ISSUE TITLE
Specify minimum required Node version?

### ISSUE THREAD

**Issue by moollaza** [semencov/tailwindcss-font-inter#4]
I ran into issues using this lib because `Object.fromEntries()` is not available in Node v10, which I was using.

Perhaps the package.json should indicate the minimum required version of node? I think its v12

**Comment by semencov** [comment]
Thank you for report. I've replaced `Object.fromEntries()` with lodash methods (anyway TailwindCSS depends on it) in v1.0.8. Tested on Node v10.16. So could you update and test it?

Didn't specified minimum version yet. Will configure CI to test on different Node versions later to make it right.

**Comment by moollaza** [comment]
@semencov thanks a lot!

> So could you update and test it?

I ended up switching to Node v12, but should be able to switch back and test :+1:

**Comment by moollaza** [comment]
Confirmed it worked with Node V10.17.0 👍 

Thanks again @semencov
