### ISSUE TITLE
font-size: [object Object]

### ISSUE THREAD

**Issue by richardthombs** [semencov/tailwindcss-font-inter#7]
I'm seeing invalid CSS when I enable this plugin:

![image](https://user-images.githubusercontent.com/1511599/109144383-04210680-7759-11eb-81cc-e849d9daa901.png)

Edit: Sorry, should have said that this is Tailwind 2.0.2 and tailwindcss-font-inter 2.0.1

**Comment by semencov** [comment]
Please see https://github.com/semencov/tailwindcss-font-inter/issues/8#issuecomment-788886875

The issue has the same causes as #8
